### ISSUE TITLE
차트쪽 예제가 정상동작하지않습니다 (Chart example does not work)

### ISSUE THREAD

**Issue by SangPilPark** [QtExcel/QXlsx#10]
Document xlsx;
    for (int i=1; i<10; ++i) {
        xlsx.write(i, 1, i*i*i);   //A1:A9
        xlsx.write(i, 2, i*i); //B1:B9
        xlsx.write(i, 3, i*i-1); //C1:C9
    }
    //![0]

    //![1]
    Chart *pieChart = xlsx.insertChart(3, 3, QSize(300, 300));
    pieChart->setChartType(Chart::CT_Pie);
    pieChart->addSeries(CellRange("A1:A9"));
    pieChart->addSeries(CellRange("B1:B9"));
    pieChart->addSeries(CellRange("C1:C9"));

    Chart *pie3DChart = xlsx.insertChart(3, 9, QSize(300, 300));
    pie3DChart->setChartType(Chart::CT_Pie3D);
    pie3DChart->addSeries(CellRange("A1:C9"));

    Chart *barChart = xlsx.insertChart(23, 3, QSize(300, 300));
    barChart->setChartType(Chart::CT_Bar);
    barChart->addSeries(CellRange("A1:C9"));

    Chart *bar3DChart = xlsx.insertChart(23, 9, QSize(300, 300));
    bar3DChart->setChartType(Chart::CT_Bar3D);
    bar3DChart->addSeries(CellRange("A1:C9"));
/*
    Chart *lineChart = xlsx.insertChart(43, 3, QSize(300, 300));
    lineChart->setChartType(Chart::CT_Line);
    lineChart->addSeries(CellRange("A1:C9"));

    Chart *line3DChart = xlsx.insertChart(43, 9, QSize(300, 300));
    line3DChart->setChartType(Chart::CT_Line3D);
    line3DChart->addSeries(CellRange("A1:C9"));

    Chart *areaChart = xlsx.insertChart(63, 3, QSize(300, 300));
    areaChart->setChartType(Chart::CT_Area);
    areaChart->addSeries(CellRange("A1:C9"));

    Chart *area3DChart = xlsx.insertChart(63, 9, QSize(300, 300));
    area3DChart->setChartType(Chart::CT_Area3D);
    area3DChart->addSeries(CellRange("A1:C9"));
*/
    Chart *scatterChart = xlsx.insertChart(83, 3, QSize(300, 300));
    scatterChart->setChartType(Chart::CT_Scatter);
    //Will generate three lines.
    scatterChart->addSeries(CellRange("A1:A9"));
    scatterChart->addSeries(CellRange("B1:B9"));
    scatterChart->addSeries(CellRange("C1:C9"));

    Chart *scatterChart_2 = xlsx.insertChart(83, 9, QSize(300, 300));
    scatterChart_2->setChartType(Chart::CT_Scatter);
    //Will generate two lines.
    scatterChart_2->addSeries(CellRange("A1:C9"));

    Chart *doughnutChart = xlsx.insertChart(103, 3, QSize(300, 300));
    doughnutChart->setChartType(Chart::CT_Doughnut);
    doughnutChart->addSeries(CellRange("A1:C9"));

    //![1]

    //![2]
    xlsx.saveAs("Book1.xlsx");
    //![2]

상단의 주석표시된 부분의 코드를 동작시키면 엑셀파일이 깨졌다고 나옵니다.
현재저는 Office 2016을 사용중입니다.
감사합니다.

**Comment by j2doll** [comment]
이슈 보고 감사합니다. 
사실 오피스2016에서는 한번도 테스트 해본적이 없었습니다--;

**Comment by SangPilPark** [comment]
수정 감사합니다 :D

**Comment by j2doll** [comment]
Issue #10 has been resolved.
Please test.

:kr: 
이슈 #10번이 해결되었습니다. 
테스트 해주세요.

**Comment by SangPilPark** [comment]
네 시간되는데로 코멘트 추가 할게요

**Comment by SangPilPark** [comment]
정상작동합니다 :)

**Comment by j2doll** [comment]
I'll close this issue.
:kr: 이슈 종료합니다.
