### ISSUE TITLE
Error opening xlsx after put image

### ISSUE THREAD

**Issue by olivierlopez44** [QtExcel/QXlsx#113]
Hi everybody,

i try to add image on my sheet.
Howewer when i use my xlsx file i got an error.
I'm an Qt4.8, same on Qt5.15.

My code:
xlsx.addSheet(tr("Résumé"));
QImage myImage = _graphGroup->toPixmap(50,50).toImage();
int index = xlsx.insertImage( 1, 1, myImage );

**Comment by olivierlopez44** [comment]
No answer from the dev ?

**Comment by j2doll** [comment]
Dear @olivierlopez44 

Can I see publicly available test code?
All files including project files.

Me or others may help you.

**Comment by olivierlopez44** [comment]
I've tested in blak project so i got nothing special on it.

**Comment by olivierlopez44** [comment]
Old version of the project, now it's work on QT 5.15
