### ISSUE TITLE
QZip: not a zip file!

### ISSUE THREAD

**Issue by wangyuou** [QtExcel/QXlsx#119]
I use WPS to create XLS file, and then I want to read it through qtxlsx, but I received an error qzip: not a zip file! Thank you very much

**Comment by wangyuou** [comment]
解决了

**Comment by helywin** [comment]
您好，怎么解决的，方便说一下吗？

**Comment by j2doll** [comment]
Dear @wangyuou 

Can you upload your example file for testing?

**Comment by helywin** [comment]
Hello @j2d0ll

I finally found out that my file is in XLS format which generated by Python xlwt, maybe that is the problem.

**Comment by j2doll** [comment]
Dear @helywin 
I open test.zip. But I failed to open test.xlsx using Microsoft Excel.

**Comment by helywin** [comment]
> 
> 
> Dear @helywin
> I open test.zip. But I failed to open test.xlsx using Microsoft Excel.

you can open it by change it's extension name to `.xls`
