### ISSUE TITLE
save th execl but the process don't exit

### ISSUE THREAD

**Issue by LiuLikeQian** [QtExcel/QXlsx#138]
i found the sourse code, there are many files were opened and hadn't be closed, and when i save the excel then exeit my process,
i uesed Process Hacker 2 check the excel process, and found  Residual process which i open the excel.

**Comment by LiuLikeQian** [comment]
if u use QAXobject，and don't delete it codes, it will be create excel process....

**Comment by j2doll** [comment]
:one: QXlsx do not use QAXobject.
:two:  I don't know how to use Process Hacker 2, so I don't know why.
If someone, reading this article, knows why , ask for help.

**Comment by LiuLikeQian** [comment]
sorry ,this is my misstake.thanks for your anwser. so&nbsp; i have closed this question.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QtExcel/QXlsx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月12日(星期五) 晚上8:13
收件人:&nbsp;"QtExcel/QXlsx"<QXlsx@noreply.github.com&gt;;
抄送:&nbsp;"流若浅"<764460607@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [QtExcel/QXlsx] save th execl but the process don't exit (#138)





 
1️⃣ QXlsx do not use QAXobject.
 2️⃣  I don't know how to use Process Hacker 2, so I don't know why.
 If someone, reading this article, knows why , ask for help.
