### ISSUE TITLE
how can i get the Rows or Columns？

### ISSUE THREAD

**Issue by LiuLikeQian** [QtExcel/QXlsx#143]
i checked the code and not found there is not api can get all the rows and columns.

**Comment by j2doll** [comment]
Dear @LiuLikeQian 

See 5th example of https://github.com/QtExcel/QXlsx/wiki#examples

**Comment by LiuLikeQian** [comment]
thanks for your kind.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QtExcel/QXlsx"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 晚上7:41
收件人:&nbsp;"QtExcel/QXlsx"<QXlsx@noreply.github.com&gt;;
抄送:&nbsp;"流若浅"<764460607@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [QtExcel/QXlsx] how can i get the Rows or Columns？ (#143)





 
Dear @LiuLikeQian
 
See 5th example of https://github.com/QtExcel/QXlsx/wiki#examples
