### ISSUE TITLE
cell border style is incorrect

### ISSUE THREAD

**Issue by devRyeong** [QtExcel/QXlsx#149]
![5_2cell](https://user-images.githubusercontent.com/80737192/111403218-f9caaa80-870f-11eb-8cec-7a365672c4c6.PNG)

(5,2) cell's left border style isn't 'BorderNone'
but  the result is as follows when i read this style in qt.

            qDebug()<<"top : "<<sheet->cellAt( 5, 2 )->format().topBorderStyle();
            qDebug()<<"bottom : "<<sheet->cellAt( 5, 2 )->format().bottomBorderStyle();
            qDebug()<<"left : "<<sheet->cellAt( 5, 2 )->format().leftBorderStyle();
            qDebug()<<"right : "<<sheet->cellAt( 5, 2 )->format().rightBorderStyle();

![Debug result](https://user-images.githubusercontent.com/80737192/111403941-3a76f380-8711-11eb-8f71-1c4c23be2ac5.PNG)

0 = 'BorderNone'
1 = 'BorderThin'

**Comment by j2doll** [comment]
Dear @devRyeong 

Can I see the excel file and example code you used? Maybe someone can help you.
