### ISSUE TITLE
How to write in an existing file

### ISSUE THREAD

**Issue by T-berton** [QtExcel/QXlsx#166]
Hi,
I have to make a project in which I have to write information in an already existing excel file. However, I have no idea how to do it. I tested this piece of code, in which I load my existing file and write Hello Qt but the problem is that the whole existing file has been replaced by Hello Qt.
I would like my existing file to keep its formatting and then I can fill it with informations.

Thanks a lot for your help!

![image](https://user-images.githubusercontent.com/62552713/123780760-d0efaf00-d8d3-11eb-86f6-9579977ee32d.png)

**Comment by T-berton** [comment]
Ok guys, I have solved my problem. The solution is to make sure that the file you want to modify is placed in the path of the exe.
I have another question. When I do the "saveAs" function, my XLS file saves in the exe folder, is there any way to save the file in another folder? 
Thanks very much for your help !

**Comment by j2doll** [comment]
> Ok guys, I have solved my problem. The solution is to make sure that the file you want to modify is placed in the path of the exe.
> Thanks!

Sorry for the late reply. 
I am currently working in a place where there is no internet.

If you post publicly available code, I and others may be able to help you.

> Because I don't speak English as my first language, my English may sound strange.

**Comment by T-berton** [comment]
Thanks for your answer ! I have solved my last problem but i have got another one. I am trying to write in an existing file. The problem is that this file has a header and this header disappears when i save my file.

Here some pictures you will understand.
![image](https://user-images.githubusercontent.com/62552713/127662305-0742be0b-68ff-4805-ad5b-a3c3010a47b7.png)
In this picture you can see my existing file which i want to modify.

But when i write into this file the header "Test production" disappears, here you can see a picture 
![image](https://user-images.githubusercontent.com/62552713/127662231-71dbaca0-956f-4db3-bc38-e71003cea9ac.png)

Thank your for your help !

**Comment by T-berton** [comment]
Here is the code : 

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    // qDebug() << "[debug] current directory is " << QDir::currentPath();

    Document doc("myfile.xlsx");
    if (doc.load()) // load excel file
    {
        printf("work well");
        QVariant writeValue = QString("Hello Qt"); 
        int row = 5; int col = 1;
        doc.write("A1",writeValue);
        doc.saveAs("C:/Users/Documents/TestXlsx/my_file.xlsx");
    }
    else
        printf("failed");

    return 0;
}

**Comment by j2doll** [comment]
Dear @T-berton 
I'm glad you got it resolved.
If you post example code in the future, I or others may be able to help. 😄
