### ISSUE TITLE
Qt 6.1.2 : QVariant::type() const' is deprecated: Use metaType()

### ISSUE THREAD

**Issue by fverneau** [QtExcel/QXlsx#171]
Why not to change in xlsxcell.cpp :
`if ( vDT.type() == QVariant::DateTime )
        {
            ret = vDT;
        }
        else if ( vDT.type() == QVariant::Date )
        {
            ret = vDT;
        }
        else if ( vDT.type() == QVariant::Time )
        {
            ret = vDT;
        }`
with 
`        if ( vDT.metaType().id() == QMetaType::QDateTime )
        {
            ret = vDT;
        }
        else if ( vDT.metaType().id() == QMetaType::QDate )
        {
            ret = vDT;
        }
        else if ( vDT.metaType().id() == QMetaType::QTime )
        {
            ret = vDT;
        }`

**Comment by j2doll** [comment]
Dear @fverneau 

Thanks for checking.  :+1:

It seems to be caused by the version difference between Qt5 and Qt6.

https://www.qt.io/blog/whats-new-in-qmetatype-qvariant

```
Note also that QVariant::Type and its related methods have been deprecated in Qt 6 (but still exist). 
A replacement API working with QMetaType::Type has been added. 
```
