### ISSUE TITLE
Suggest QStringLiteral in xlsxcolor.cpp lines 125 and 134

### ISSUE THREAD

**Issue by ransbotham3** [QtExcel/QXlsx#180]
File xlsxcolor.cpp now contains literal strings in lines 125 and 134.

```cpp    
QColor color;
QString strColor = QStringLiteral( "00000000" );

if ( c.length() == 8 )
{
     strColor = c;
}

if ( c.length() == 6 )
{
     strColor = QStringLiteral( "00" ) + c;
}
```

If changed to use QStringLiteral, I think the code would compile with the QT_NO_CAST_FROM_ASCII option.

Regards

**Comment by j2doll** [comment]
Dear @ransbotham3 

Thanks for reporting.

**Comment by dantti** [comment]
QLatin1String is a better fit for this, I have fixed this in https://github.com/QtExcel/QXlsx/pull/176
