### ISSUE TITLE
Can't compile with Qt 6.3.1

### ISSUE THREAD

**Issue by luigi-pirillo** [QtExcel/QXlsx#212]
On Windows 10, opening and compile QXlsx.pro project, I get the following error:
Unknown type name QStringRef on row 2415, file xlsxworksheet.cpp

I think can't find the core5compat module

**Comment by dantti** [comment]
can you replace QStringRef with auto there and see if it fixes your issue?

**Comment by luigi-pirillo** [comment]
In this way:

const auto& typeString = attributes.value(QLatin1String("t"));

it seems to compile and work.

Thanks for your advice!
