### ISSUE TITLE
After exiting main, the program crashes

### ISSUE THREAD

**Issue by skyzhou95** [QtExcel/QXlsx#225]
![image](https://user-images.githubusercontent.com/46395124/179878250-fca63baa-318a-458e-b254-a68b7326ab9b.png)
![image](https://user-images.githubusercontent.com/46395124/179888139-9a014f66-b7be-4af8-b6c6-8d342790e638.png)

```cpp
int main(int argc, char *argv[])
{
    QCoreApplication app(argc, argv);
    Document xlsxR("Test.xlsx");
    if ( xlsxR.load() ) // load excel file
    {
        int row = 1; int col = 1;
        Cell* cell = xlsxR.cellAt(row, col); // get cell pointer.
        QVariant var = cell->readValue(); // read cell value (number(double), QDateTime, QString ...)
        qDebug() << "[debug] cell(1,1) is " << var; // Display value. It is 'Hello Qt!'.
    }

    return 0;
}
```
![image](https://user-images.githubusercontent.com/46395124/179887786-6eb194b0-8081-4966-b300-3664dd1b3f65.png)

Are there compatibility issues and requirements on the QT version or compiler version?

**Comment by TrafalgarSX** [comment]
> Dear @skyzhou95
> 
> Sorry for the late reply.
> 
> I'm not sure what the cause is. Does the error occur even if you configure it like this?
> 
> ```c++
> int main(int argc, char *argv[])
> {
>     QCoreApplication app(argc, argv);
> 
>     {
>         using namespace QXlsx;
>         Document xlsxR("Test.xlsx");
>         if ( xlsxR.load() ) // load excel file
>         {
>             int row = 1; int col = 1;
>             Cell* cell = xlsxR.cellAt(row, col); // get cell pointer.
>             QVariant var = cell->readValue(); // read cell value (number(double), QDateTime, QString ...)
>             qDebug() << "[debug] cell(1,1) is " << var; // Display value. It is 'Hello Qt!'.
>         }
>     }
> 
>     return 0;
> }
> ```

yes, I have the same problem.

**Comment by dantti** [comment]
cellAt will return nullptr if not valid, you should check it first
