### ISSUE TITLE
Can't find a way how to read cell background fill color

### ISSUE THREAD

**Issue by AlexeiStrakhov** [QtExcel/QXlsx#26]
I have some XLSX file. Some cells have solid color filled background. But don't know how to read this color.

**Comment by j2doll** [comment]
Dear @AlexeiStrakhov

Thank you for your feedback.

QXlsx does not support background color.

I will register for the issue as an enchantment.

**Comment by j2doll** [comment]
Hi. @AlexeiStrakhov 

I have modified some of the style handling.

Copycat example shows how to set the background color.
```cpp
// XlsxTab.cpp
{
    QColor clrForeGround = ptrCell->format().patternForegroundColor();
    if ( clrForeGround.isValid() )
    {
          // qDebug() << "[debug] ForeGround : " << clrForeGround;
    }

    QColor clrBackGround = ptrCell->format().patternBackgroundColor();
    if ( clrBackGround.isValid() )
    {
          // TODO: You must use various patterns.
          newItem->setBackground( Qt::SolidPattern );
          newItem->setBackgroundColor( clrBackGround );
    }
}
```

Test for new revisions.
