### ISSUE TITLE
Sheets, rows and columns iteration

### ISSUE THREAD

**Issue by tevenfeng** [QtExcel/QXlsx#36]
I'm just wondering whether there's a way to iterate among the sheets, rows and columns. Because I could not find a way to get the number of rows and columns. Thanks!

**Comment by j2doll** [comment]
See copycat example.

bool XlsxTab::setSheet()
...
    // get full cells of sheet
    int maxRow = -1;
    int maxCol = -1;
    QVector<CellLocation> clList = wsheet->getFullCells( &maxRow, &maxCol );
....

**Comment by tevenfeng** [comment]
Wow, thanks a lot bro! I will have a look at that!

**Comment by j2doll** [comment]
I'll close this issue.
