### ISSUE TITLE
Print setting is changed after write the excel file 

### ISSUE THREAD

**Issue by liufeijin** [QtExcel/QXlsx#37]
Dear J2doll

There is a problem that the print setting will be changed.
Seems it  appears from the formula problem was resolved.
original :
![Original1](https://user-images.githubusercontent.com/19425403/58488118-65d6ca00-819b-11e9-993a-647a2d4e96cd.png)
![OriginalSheet2](https://user-images.githubusercontent.com/19425403/58488127-696a5100-819b-11e9-84ea-bc202b92381f.png)

after write
![afterwrite](https://user-images.githubusercontent.com/19425403/58488154-71c28c00-819b-11e9-89b4-1d7d946c38b5.png)
![afterwriteSheet2](https://user-images.githubusercontent.com/19425403/58488168-78e99a00-819b-11e9-8353-2b74516cc207.png)

[sample excel file.zip](https://github.com/QtExcel/QXlsx/files/3228243/sample.excel.file.zip)

Cloud you have a look ?
best regards,
liu

**Comment by j2doll** [comment]
Hi. I registered as a bug issue.

**Comment by liufeijin** [comment]
Could you have a look how to resolve it?
If you have time kindly PLS help to resolve it ?
It is a big problem that to be need to munch time to adjust back the print setting 1 by 1 sheet.
Best regards,
jeff

**Comment by j2doll** [comment]
Dear @liufefeijin

I was not able to pinpoint the issue because of my busy schedule.  
Because this project is an open source project, so no one knows when the issue is resolved.  
Of course I will do my best.

**Comment by liufeijin** [comment]
Dear j2doll
I rename the excel file name from *.xlsx to *.zip  and found problem is lose the whole printerSettings under Xl folder .
![1](https://user-images.githubusercontent.com/19425403/59729627-c7a5c380-9271-11e9-9dcd-8fa7421756a0.png)
I try to copy the whole folder from the original to the modified excel file by QXlsx , but it is no effect.
I think will be have other mark to be add .
Cloud you help to have a look?
attachments are the original and modified file for your reference.
best regards, 
jeff

[sampley.zip](https://github.com/QtExcel/QXlsx/files/3303996/sampley.zip)

[modified.zip](https://github.com/QtExcel/QXlsx/files/3303998/modified.zip)

**Comment by liufeijin** [comment]
it is resolved .

**Comment by j2doll** [comment]
I have checked the issue now.  
I'm glad that the issue has been resolved.  
I created a new release.
