### ISSUE TITLE
soversion

### ISSUE THREAD

**Issue by DarthGandalf** [QtExcel/QXlsx#375]
Hi, 35c6d274cbbe5eb1437bde9f7ed7e3a0fc9e9ece looks like an ABI change, but I see the SOVERSION in https://github.com/QtExcel/QXlsx/blob/master/QXlsx/CMakeLists.txt is based on the `${PROJECT_VERSION}` therefore is still 1.4.4

Shouldn't it have been updated?

I don't really check the diff for every release, but soversion should be bumped for every release with ABI changes, otherwise a program which was built for old QXlsx will now try to call functions of new QXlsx and crash, cause memory corruption or other bugs, because it treated the object returned from the function as `Cell*` while in fact it is `std::shared_ptr<Cell>` which has different memory layout.

The safest way (if you're not sure) would be to bump the soversion every release (just keep it in sync with the actual version number), but if you know that ABI didn't change since last release, it's fine to skip keep the old soversion for that release.

**Comment by dantti** [comment]
I'm pushing a fix but don't expect proper ABI bumps, it's better to use this library as a static one as it's quite volatile

**Comment by DarthGandalf** [comment]
Thanks

> it's quite volatile

Then probably it makes sense to update it every release (keep them in sync)
