### ISSUE TITLE
Optimized cell storage, May be more efficient

### ISSUE THREAD

**Issue by YtxErp** [QtExcel/QXlsx#378]
https://github.com/QtExcel/QXlsx/blob/0333829478e2f2674ee89512fa6508235bdb3e35/QXlsx/header/xlsxworksheet_p.h#L178

Hi,
I noticed that the current implementation uses `QHash<int, QHash<int, QSharedPointer<Cell>>`.
How about replacing it with `QMap<std::pair<int, int>, std::shared_ptr<Cell>>`?

**Comment by dantti** [comment]
well, sadly if you read the comment abouve that line it's because of Qt5 we can't do this. Also QMap is definetly too slow for our use case.
