### ISSUE TITLE
Normal Formula are not working

### ISSUE THREAD

**Issue by WalSpek** [QtExcel/QXlsx#38]
Excel xlsx files stores "normal" Formulars in other ways than implemented.

Please see the following change, it is correct in the former version:

bool CellFormula::loadFromXml(QXmlStreamReader &reader)
{
    Q_ASSERT(reader.name() == QLatin1String("f"));
    if (!d)
        d = new CellFormulaPrivate(QString(), CellRange(), NormalType);

    QXmlStreamAttributes attributes = reader.attributes();
    QString typeString = attributes.value(QLatin1String("t")).toString();

    // branch: shared-formula
    //
    if (typeString == QLatin1String("array")) {
        d->type = ArrayType;
    }
    else if (typeString == QLatin1String("shared")) {
        d->type = SharedType;
    }
    else if (typeString == QLatin1String("normal")) { // will never ocure in xlsx files.
        d->type = NormalType;
    }
    else if (typeString == QLatin1String("dataTable")) {
        d->type = DataTableType;
    }
    else {
		d->type = NormalType; // Change: normal Type is not mentioned in the xml file!!!!!
    }

**Comment by j2doll** [comment]
Dear @WalSpek 
Thanks for reporting a issue.
I registered as a temporary bug.

**Comment by j2doll** [comment]
I'm working on a branch called dev40. Please test dev40.

**Comment by WalSpek** [comment]
Tested and OK!

 

 

 

Mit freundlichen Grüßen

Best regards

 

 

Walter Eglseer, MBA

Geschäftsleitung / Managing Director

 

Spektra LED Gmbh

Licht- und EnergieDienstleistungen

Erlau 5

4770 Andorf

Austria

 

Mobil: +43 699 11 34 35 36

email: w.eglseer@spektraled.at <mailto:email:%20w.eglseer@spektraled.at> 

 <http://www.spektraled.at/> http://www.spektraled.at

 



 

 

HINWEIS: Dies ist eine vertrauliche Nachricht und nur für den Adressaten bestimmt. Es ist nicht erlaubt, diese Nachricht zu kopieren oder Dritten zugaenglich zu machen. Sollten Sie irrtuemlich diese Nachricht erhalten haben, bitte ich um Ihre Mitteilung per E-Mail oder unter der oben angegebenen Telefonnummer.

Privileged/Confidential Information may be contained in this message. If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), you may not copy or deliver this message to anyone. In such case, you should destroy this message, and notify us immediately. If you or your employer does not consent to Internet E-Mail messages of this kind, please advise us immediately. Opinions, conclusions and other information expressed in this message are not given or endorsed by my firm or employer unless otherwise indicated by an authorized representative.

 

 

Von: Jay Two <notifications@github.com> 
Gesendet: Samstag, 1. Juni 2019 16:56
An: QtExcel/QXlsx <QXlsx@noreply.github.com>
Cc: WalSpek <w.eglseer@spektraled.at>; Mention <mention@noreply.github.com>
Betreff: Re: [QtExcel/QXlsx] Normal Formula are not working (#38)

 

I'm working on a branch called dev40. Please test dev40.

**Comment by j2doll** [comment]
Dear @WalSpek

Could you re-register as a new issue? 
The line breaks in the article are strange, making it difficult to see the contents.

**Comment by j2doll** [comment]
I merged dev40 branch to master branch.
I'll close this issue.
