### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by wanghuqiang123** [QtExcel/QXlsx#40]
Hello, I am a beginner, I want to use Qt to process EXCEL sheets, I like your library, also, I have never used github, so I would like to ask if there is any reference document about QXlsx?

**Comment by alexpennington** [comment]
Just becoming acquainted with the project myself.  For a place to start look at the following link to the project documentation.

https://github.com/QtExcel/QXlsx/blob/master/HowToSetProject.md

**Comment by wanghuqiang123** [comment]
> Just becoming acquainted with the project myself. For a place to start look at the following link to the project documentation.
> 
> https://github.com/QtExcel/QXlsx/blob/master/HowToSetProject.md

I actually learned a little programming

**Comment by liufeijin** [comment]
> > Just becoming acquainted with the project myself. For a place to start look at the following link to the project documentation.
> > https://github.com/QtExcel/QXlsx/blob/master/HowToSetProject.md
> 
> I actually learned a little programming
程序使用说明请参考
http://qtxlsx.debao.me/

**Comment by j2doll** [comment]
Hi.  nice to meet you.  
I recommend that you study in the following order. 
1. C++ : study old c and c++(such as c++98), then, study modern c++
2. Qt : first, study 'core' component
3. Read markdown of current project
4. See examples of current project
