### ISSUE TITLE
Can not build through VS2015&Qt5.8.0 after I finished the configuration.

### ISSUE THREAD

**Issue by yazhouzheng** [QtExcel/QXlsx#43]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: virtual int __cdecl QXlsx::Document::qt_metacall(enum QMetaObject::Call,int,void * *)" (?qt_metacall@Document@QXlsx@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z)	QtExecelTest	D:\asher\project\QtExecelTest\QtExecelTest\xlsxdocument.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: virtual struct QMetaObject const * __cdecl QXlsx::Document::metaObject(void)const " (?metaObject@Document@QXlsx@@UEBAPEBUQMetaObject@@XZ)	QtExecelTest	D:\asher\project\QtExecelTest\QtExecelTest\xlsxdocument.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: virtual void * __cdecl QXlsx::Document::qt_metacast(char const *)" (?qt_metacast@Document@QXlsx@@UEAAPEAXPEBD@Z)	QtExecelTest	D:\asher\project\QtExecelTest\QtExecelTest\xlsxdocument.obj	1

**Comment by yazhouzheng** [comment]
Is this a configuration problem or lack of lib?

**Comment by yazhouzheng** [comment]
Fixed it by add headers to projects.

**Comment by j2doll** [comment]
Dear @yazhouzheng 

Thank you for using QXlsx.

Is this issue resolved?
