### ISSUE TITLE
QXlsx as a DLL

### ISSUE THREAD

**Issue by PMime** [QtExcel/QXlsx#49]
We like to use QXlsx as a DLL in our project and found that QXlsx is arranged for a static LIB. By studying the code it occured to us that the macro Q_XLSX_EXPORT is missing in the header files compared to QtXlsx.

Is it possible to change the project, so that it is possible to create DLLs with little effort? Thanks in advance!

**Comment by j2doll** [comment]
Dear @PMime 

I intentionally deleted that macro. 
Because DLL and SO have complex problems in distributing executables.

Of course, you can put that macro in the class you want to use. (such as doc, worksheet, cell, etc)
Because this project is open source.

**Comment by dantti** [comment]
What complex problems did you have?
I have several Qt/CMake projects that can be compiled as both things, and people use it without issues on any OS.
Cutelyst for example is even on VCPKG, changing BUILD_SHARED_LIBS to off will build it in static mode, pretty trivial.

**Comment by j2doll** [comment]
Thanks for reporting.

For easy support of iPhone, Android, car software, etc., I was not supporting DLL.

I will register as an enhancement how to support DLL and LIB.

**Comment by dantti** [comment]
Well as I said you can have both, would you accept PR if I proper turn this into a CMake project?
I'm also working on getting rid of GUIPrivate as that would break things when used as dynamic library

**Comment by j2doll** [comment]
Sorry for the late response.
Please upload a pull request.
This project is an open source project and help is always welcome.

**Comment by KangLin** [comment]
> Well as I said you can have both, would you accept PR if I proper turn this into a CMake project?
> I'm also working on getting rid of GUIPrivate as that would break things when used as dynamic library

I suggest to reimplement QZipWriter in the project. See #55

**Comment by dantti** [comment]
yeah, sadly I got too busy with another project didn't manage to make all changes I wanted to, Qt upstream indeed suggests to just copy their implementation.

**Comment by KangLin** [comment]
> yeah, sadly I got too busy with another project didn't manage to make all changes I wanted to, Qt upstream indeed suggests to just copy their implementation.

OK. I copy it.

**Comment by dand-oss** [comment]
You don't need a macro

Cmake can handle for you in one line

Create dlls on Windows without declspec() using new CMake export all feature
July 24, 2015
https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/

Implemented here
support shared and static libraries #127

**Comment by dantti** [comment]
> You don't need a macro
> 
> Cmake can handle for you in one line
> 
> Create dlls on Windows without declspec() using new CMake export all feature
> July 24, 2015
> https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/
> 
> Implemented here
> support shared and static libraries #127

What about private classes that you don't want to export, from the name and a quick read it seems it exports ALL symbols which isn't something desired in most projects

**Comment by dand-oss** [comment]
> What about private classes that you don't want to export, from the name and a quick read it seems it exports ALL symbols which isn't something desired in most projects

How do you handle that in llinking your static library -which is the only option now?

**Comment by dantti** [comment]
I simply don't mark the private classes to be exported.

**Comment by dand-oss** [comment]
I can understand limiting the number of symbols to prevent linker table overflow in Visual S.

Although not all systems would exceed this
and there are compiler and linker options to mitigate this effect
And dynamic loading "LoadLibrary()" on the DLLs rather than static linking an import library for the dll.

Thus its a judgement call on whether

annotating every large API by hand and then maintaining those annotations as the library evolves

is **worth the effort**.

One could consider WINDOWS_EXPORT_ALL to be the equivalent of static linking 
- any symbols in "obj references table" introspected by cmake would ALSO be seen by linker!
while still sharing the library across dlls.

Your question "how to limit export all" invites examining implementation detail.

Implementation in cmake about 80 lines
https://github.com/Kitware/CMake/blob/master/Source/cmGlobalVisualStudioGenerator.cxx#L868

Cmake queries the objs for symbols, writes them to "objects.txt" then combines with module *.def you specify to automate a module definition for shared library.

Exporting from a DLL Using DEF Files
https://docs.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-def-files?view=msvc-160

Q> you don't want to export
ANS: We could manipulate the def file (or create a different one) before linking to achieve "limiting auto exports".

**Comment by j2doll** [comment]
There have been many good conversations.
I have read the article now.
It's in a place where the internet is not available on weekdays. 😭

**Comment by Jihadist** [comment]
Why did you drop modern cmake with exporting cmake config file and possibility to build shared lib https://github.com/QtExcel/QXlsx/commit/dddf63eb48e0a2812d8d559edc515a6e437163b7#diff-f2d2dde2d868d22fc4961cc942d539887b1147df237fe2016f24dd29b48d4daa and replace it with another cmakelists with configs and hardcoded only static lib?

**Comment by j2doll** [comment]
> Why did you drop modern cmake with exporting cmake config file and possibility to build shared lib [dddf63e#diff-f2d2dde2d868d22fc4961cc942d539887b1147df237fe2016f24dd29b48d4daa](https://github.com/QtExcel/QXlsx/commit/dddf63eb48e0a2812d8d559edc515a6e437163b7#diff-f2d2dde2d868d22fc4961cc942d539887b1147df237fe2016f24dd29b48d4daa) and replace it with another cmakelists with configs and hardcoded only static lib?

Dear @Jihadist 

I have modified the files to make cmake build on both Qt5 and Qt6.
This is because there is still a lot of code that uses Qt5 in commercial projects.

> Sorry for the late reply. I work in a place where there is no internet on weekdays.

**Comment by Jihadist** [comment]
> 
> 
> > Why did you drop modern cmake with exporting cmake config file and possibility to build shared lib [dddf63e#diff-f2d2dde2d868d22fc4961cc942d539887b1147df237fe2016f24dd29b48d4daa](https://github.com/QtExcel/QXlsx/commit/dddf63eb48e0a2812d8d559edc515a6e437163b7#diff-f2d2dde2d868d22fc4961cc942d539887b1147df237fe2016f24dd29b48d4daa) and replace it with another cmakelists with configs and hardcoded only static lib?
> 
> Dear @Jihadist
> 
> I have modified the files to make cmake build on both Qt5 and Qt6.
> This is because there is still a lot of code that uses Qt5 in commercial projects.
> 
> > Sorry for the late reply. I work in a place where there is no internet on weekdays.

I use old version of cmake script and it works ok with Qt5. You dropped support for dynamic linkage and correct cmake usage aka FindPackage in new cmake script. 
In old script you only two fix two lines for support Qt6
```
find_package(Qt5 CONFIG REQUIRED COMPONENTS Gui)
```
and
```
target_link_libraries(QXlsx PUBLIC Qt5::Gui Qt5::GuiPrivate)
```
So i dont see any reason to rewrite it whole. I dont know why Qt Company doesnt describe the universal cmake script for Qt5 and Qt6 here https://doc.qt.io/qt-6/cmake-get-started.html but you can find it here https://doc-snapshots.qt.io/qt6-dev/cmake-qt5-and-qt6-compatibility.html#supporting-older-qt-5-versions

**Comment by j2doll** [comment]
I don't know the exact solution right now. 
I will keep this issue until a good solution is found.
Thanks for reporting.

**Comment by Jihadist** [comment]
@j2doll maybe the good solution is https://github.com/Jihadist/QXlsx/commit/1a078b664dec302677129099b342ae7ca77cc7b9 look please, I reword a bit old CMakeLists to provide compatibility with qt6

**Comment by j2doll** [comment]
> @j2doll maybe the good solution is [Jihadist@1a078b6](https://github.com/Jihadist/QXlsx/commit/1a078b664dec302677129099b342ae7ca77cc7b9) look please, I reword a bit old CMakeLists to provide compatibility with qt6

committed to branch qt6-5.

**Comment by Jihadist** [comment]
@j2doll wow, thank you! Is there any info when it will be in release?

**Comment by j2doll** [comment]
Dear @Jihadist 
Sorry for the late reply.
I am currently working where there is no internet.
Sooner or later, when I can afford it, I'm trying to organize my preparations for release.

**Comment by dantti** [comment]
Ok so I finally got some time and created the PR that I wanted to #175.

By default it will keep building as static library, which is somehow convenient as you can then do:

```
FetchContent_Declare(
  QXlsx
  GIT_REPOSITORY https://github.com/QtExcel/QXlsx.git
  GIT_TAG        tag-or-sha-of-the-merge
  SOURCE_SUBDIR  QXlsx
)
FetchContent_MakeAvailable(QXlsx)
```
OR when shared built with -DBUILD_SHARED_LIBS=ON
```
find_package(QXlsx)
```

After that just link to it:
```
target_link_libraries(... QXlsx::Core)
```
We still need to mark which classes to export when using as shared lib, and I'll do that once this PR get's merged.
