### ISSUE TITLE
Is there any way to merge cells？

### ISSUE THREAD

**Issue by Liuyiming11** [QtExcel/QXlsx#54]
In qtableview there is a "setSpan" method to manage merged cells ,but my app is based on qml ,is there any way to merge cells in qml? I mean  what can I do to "setSpan" in tableview?

**Comment by j2doll** [comment]
Dear @Liuyiming11 

I do not know how to apply merge cells in QML.

But, Here is an example reading a merged cell:

```cpp
QList<CellRange> mergeCellRangeList = wsheet->mergedCells();
for ( int mc = 0; mc < mergeCellRangeList.size(); ++mc )
{
    CellRange mergedCellRange = mergeCellRangeList.at(mc);

    CellReference crTopLeft = mergedCellRange.topLeft();
    int tlCol = crTopLeft.column();
    int tlRow = crTopLeft.row();

    CellReference crBottomRight = mergedCellRange.bottomRight();
    int brCol = crBottomRight.column();
    int brRow = crBottomRight.row();

    // ...
}
```

**Comment by Liuyiming11** [comment]
Thanks for your reply.
I konw the Qt5.13 has a new tableview,I will have a try.

**Comment by j2doll** [comment]
I will close this issue.
Please reopen the issue if you wish to proceed further with this item.
