### ISSUE TITLE
Request for participation

### ISSUE THREAD

**Issue by GitterRalf** [QtExcel/QXlsx#60]
In the past i used the QtXlsxWriter from "https://github.com/dbzhang800/QtXlsxWriter"
But your fork is more actual.
For my needs I have extended the chart a bit.
Extended handling for two-dimensional table with vertical and horizontal header. And swap the Header.
Also the activation of gridlines and legends.

Can I/may I check the extensions into a new branch?

Thank you

**Comment by j2doll** [comment]
Of course it's possible. Why not? 
The project is open source and anyone can participate.
Pull request for your branch.
