### ISSUE TITLE
Qt 5.14.0 QString don't have member function 'sprintf'

### ISSUE THREAD

**Issue by Rabenda** [QtExcel/QXlsx#63]
The error happened in Qt 5.14.0

QXlsx\QXlsx\source\xlsxcolor.cpp:145:11: error: 'class QString' has no member named 'sprintf'; did you mean 'asprintf'?
     color.sprintf("%02X%02X%02X%02X", c.alpha(), c.red(), c.green(), c.blue());
           ^~~~~~~
           asprintf

**Comment by j2doll** [comment]
Dear @Rabenda 

- sprintf() has Qt version-specific differences.
  - Qt 5.6 or higher version use asprintf()
    - https://doc.qt.io/archives/qt-5.5/qstring.html
    - https://doc.qt.io/archives/qt-5.6/qstring.html
  - Older Qt uses sprintf(), and it is keeped for backward compatibility. 

- See> Qt company does not recommend this approach. (in Qt 5.6)
```
Warning: We do not recommend using QString::asprintf() in new Qt code. Instead, consider using QTextStream or arg(), both of which support Unicode strings seamlessly and are type-safe. Here is an example that uses QTextStream:
```

- It can also be defined as: https://github.com/QtExcel/QXlsx/tree/dev74
```cpp
QString XlsxColor::toARGBString(const QColor &c)
{
    QString color;

#if QT_VERSION >= 0x050600 // Qt 5.6 or over
    color = QString::asprintf("%02X%02X%02X%02X", c.alpha(), c.red(), c.green(), c.blue());
#else
    color.sprintf("%02X%02X%02X%02X", c.alpha(), c.red(), c.green(), c.blue());
#endif

    return color;
}
```

**Comment by j2doll** [comment]
I will close this issue.
Please reopen the issue if you wish to proceed further with this item.

**Comment by Miho730** [comment]
Hi There,

I see you closed this issue however I got an error which like Rabenda eventhough I tried you step above

-Qt5.4.2 Version
return QString::asprintf("%02X%02X%02X%02X", c.alpha(), c.red(), c.green(), c.blue());
-error: asprintf is not a member of qstring

after got above error I replaced your solution but another error came up as follows: 
error: cannot call member function 'QString::sprintf(const char*,...)' without object

I have tried some other solutions in the internet yet I did not find the solution 
do you have any suggestions? 
thanks in advance

**Comment by dantti** [comment]
You didn't copy the solution above as the answer to your issue is clear "without object".

**Comment by Miho730** [comment]
well honestly I tried different types of above code including the exact solution that provided by j2doll. another information about my system is that I am using Windows XP

**Comment by dantti** [comment]
This should work:
```
QString color;
color.sprintf("%02X%02X%02X%02X", c.alpha(), c.red(), c.green(), c.blue());
```
this should give you the error you got:
```
QString::sprintf("%02X%02X%02X%02X", c.alpha(), c.red(), c.green(), c.blue());
```
