### ISSUE TITLE
Reading background color from excel sheet

### ISSUE THREAD

**Issue by cmorierroy** [QtExcel/QXlsx#67]
I cannot read colours from cells. Here's my code:

```
QXlsx::Document xlsx("Data/doc.xlsx");

        if (xlsx.selectSheet("Heart")==false)
        {
            qDebug() << "ERROR: COULD NOT FIND SHEET.";
        }

        //read colour from excel file
        for(int i = 1; i <= NUM_ROWS; i++ )
        {
            for(int j = 1; j <= :NUM_COLUMNS; j++)
            {
                    qDebug() << i << xlsx.read(i,j).toInt() << j;
                    qDebug() << xlsx.currentWorksheet()->cellAt(i,j)->format();
            }
        }

```
Here's the output for cells without any colours:
QXlsx::Format(QMap((3, QVariant(int, 8))(13, QVariant(int, 2))(14, QVariant(int, 1))))

Here's the output for cells with colours:
QXlsx::Format(QMap((3, QVariant(int, 8))(6, **QVariant(QXlsx::XlsxColor, QColor(ARGB 1, 0, 0, 0)** ))(13, QVariant(int, 2))(14, QVariant(int, 1))))

Clearly, it recognizes that a colour is present, but seems to think it's just a black cell. Seems like a bug to me.

**Comment by j2doll** [comment]
Dear @cmorierroy 

See issue #26 for more information.

**Comment by j2doll** [comment]
I will close this issue.
If this issue is not over, please keep it open.
