### ISSUE TITLE
Mitstype in in the method "void setTextWarp(bool textWrap)", line 176 of the file "xlsxformat.h"

### ISSUE THREAD

**Issue by leonardooyama** [QtExcel/QXlsx#75]
There is a mitstype in in the method "void setTextWarp(bool textWrap)", line 176 of the file "xlsxformat.h"

It should be setTextWrap instead.

Cheers,

Leonardo

**Comment by liufeijin** [comment]
hi leonardooyama
below is the c file for set TextWrap(bool wrap)
i don't know what is your mean.
void Format::setTextWarp(bool wrap)
{
	if (wrap && hasProperty(FormatPrivate::P_Alignment_ShinkToFit))
		clearProperty(FormatPrivate::P_Alignment_ShinkToFit);

	setProperty(FormatPrivate::P_Alignment_Wrap, wrap, false);
}

**Comment by leonardooyama** [comment]
The name of the function is wrong. 
Warp vs Wrap .

**Comment by j2doll** [comment]
Dear @leonardooyama 

Thank you for checking.

Currently, many developers do not speak English as their native language. So do I. 

If you are familiar with English, we would appreciate it if you can help us with the project. (Such as document, etc.)

**Comment by j2doll** [comment]
Function name is changed.
I will close this issue.

**Comment by leonardooyama** [comment]
I would help by sending pull requests, but I am using the zip version of the code for now.
Thanks for fixing it!
