### ISSUE TITLE
Invalid registration MetaType<XlsxColor> in Qt 4.8

### ISSUE THREAD

**Issue by gekkone** [QtExcel/QXlsx#89]
Hello, while using the library, I found a bug with this condition in versions Qt < 5.0.0 (exactly 4.8).

In xlsxstyles.cpp 30 line
```
#if QT_VERSION >= QT_VERSION_CHECK( 5, 0, 0 )
    if (QMetaType::type("XlsxColor") == QMetaType::UnknownType)
#else
    if (!QMetaType::isRegistered(QMetaType::type("XlsxColor")))
#endif
    {
        qRegisterMetaType<XlsxColor>("XlsxColor");
        qRegisterMetaTypeStreamOperators<XlsxColor>("XlsxColor");
#if QT_VERSION >= 0x050200
        QMetaType::registerDebugStreamOperator<XlsxColor>();
#endif
    }
```
`If (!QMetaType::isRegistered(QMetaType::type("XlsxColor")))` this will not work because `QMetaType::type ("XlsxColor")` returns 0 (the type is not registered yet, so it is unknown). In turn, `QMetaType::isRegistered(0)` returns true, since 0 corresponds to the void type and is registered. This is incorrect conduct for older versions of qt.

**In my opinion the best way to fix this situation is to use this code**

```
#if QT_VERSION >= QT_VERSION_CHECK( 5, 0, 0 )
    if (QMetaType::type("XlsxColor") == QMetaType::UnknownType)
#else
    if (QMetaType::type("XlsxColor") == 0
        || !QMetaType::isRegistered(QMetaType::type("XlsxColor")))
#endif
    {
        qRegisterMetaType<XlsxColor>("XlsxColor");
        qRegisterMetaTypeStreamOperators<XlsxColor>("XlsxColor");
#if QT_VERSION >= 0x050200
        QMetaType::registerDebugStreamOperator<XlsxColor>();
#endif
    }
```
I apologize for my English, I hope I was able to explain the essence of the problem, have a nice day

**Comment by j2doll** [comment]
Sorry for the late response.
Your opinion is very helpful. thank you.
See [link](https://github.com/QtExcel/QXlsx/commit/04aac01915eaca515ab8d2e828c20ecf994a90a5) for more info.
